### ISSUE TITLE
Failed to send the request: Upload Id not found in create-multipart-upload response

### ISSUE THREAD

**Issue by campidelli** [adobe/S3Mock#1169]
Hi there,

I am currently creating a simple integration test for our spring boot application, it is just one controller with some endpoints to upload and download a file. I am using TestContainers and the `S3AsyncClient` via `S3CrtAsyncClientBuilder`.

This is the log from my Application:
````
2023-06-16T18:35:17.673+12:00 DEBUG 53321 --- [           main] o.s.web.client.RestTemplate              : HTTP POST http://localhost:50195/transfer
2023-06-16T18:35:17.689+12:00 DEBUG 53321 --- [           main] o.s.web.client.RestTemplate              : Accept=[application/json, application/*+json]
2023-06-16T18:35:17.690+12:00 DEBUG 53321 --- [           main] o.s.web.client.RestTemplate              : Writing [[B@7bbe5548] with org.springframework.http.converter.ByteArrayHttpMessageConverter
2023-06-16T18:35:17.774+12:00  INFO 53321 --- [r-http-kqueue-2] a.c.acme.controller.TransferController  : UploadHandler: mediaType application/octet-stream, length=70502978, fileKey = 99aadc13-4379-41cd-8714-2acf8527845f
2023-06-16T18:35:17.780+12:00 DEBUG 53321 --- [r-http-kqueue-2] software.amazon.awssdk.request           : Sending Request: DefaultSdkHttpFullRequest(httpMethod=PUT, protocol=http, host=localhost, port=49228, encodedPath=/vanillabeanz-demo/99aadc13-4379-41cd-8714-2acf8527845f, headers=[amz-sdk-invocation-id, Content-Length, Content-Type, Expect, User-Agent, x-amz-meta-file_name], queryParameters=[])
2023-06-16T18:35:17.883+12:00 ERROR 53321 --- [nc-response-0-6] a.w.r.e.AbstractErrorWebExceptionHandler : [574b79b9-1]  500 Server Error for HTTP POST "/transfer"

software.amazon.awssdk.core.exception.SdkClientException: Failed to send the request: Upload Id not found in create-multipart-upload response
	at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:111) ~[sdk-core-2.20.78.jar:na]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ Handler au.com.acme.controller.TransferController#uploadHandler(HttpHeaders, Flux) [DispatcherHandler]
	*__checkpoint ⇢ org.springframework.web.filter.reactive.ServerHttpObservationFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ HTTP POST "/transfer" [ExceptionHandlingWebHandler]
Original Stack Trace:
		at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:111) ~[sdk-core-2.20.78.jar:na]
		at software.amazon.awssdk.core.exception.SdkClientException.create(SdkClientException.java:43) ~[sdk-core-2.20.78.jar:na]
		at software.amazon.awssdk.services.s3.internal.crt.S3CrtResponseHandlerAdapter.handleError(S3CrtResponseHandlerAdapter.java:127) ~[s3-2.20.78.jar:na]
		at software.amazon.awssdk.services.s3.internal.crt.S3CrtResponseHandlerAdapter.onFinished(S3CrtResponseHandlerAdapter.java:93) ~[s3-2.20.78.jar:na]
		at software.amazon.awssdk.crt.s3.S3MetaRequestResponseHandlerNativeAdapter.onFinished(S3MetaRequestResponseHandlerNativeAdapter.java:24) ~[aws-crt-0.21.8.jar:0.21.8]
````

This is the log from the S3Mock container
````
2023-06-16 06:35:17.576 DEBUG 1 --- [tp1733581655-21] o.s.web.servlet.DispatcherServlet        : POST "/vanillabeanz-demo/99aadc13-4379-41cd-8714-2acf8527845f?uploads", parameters={masked}
2023-06-16 06:35:17.578 DEBUG 1 --- [tp1733581655-21] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped to com.adobe.testing.s3mock.MultipartController#createMultipartUpload(String, ObjectKey, String, String, String, String, HttpHeaders)
2023-06-16 06:35:17.653 DEBUG 1 --- [tp1733581655-21] o.s.w.s.m.m.a.HttpEntityMethodProcessor  : Using 'application/xml', given [application/x-www-form-urlencoded, application/xml] and supported [application/xml]
2023-06-16 06:35:17.656 DEBUG 1 --- [tp1733581655-21] o.s.w.s.m.m.a.HttpEntityMethodProcessor  : Writing [com.adobe.testing.s3mock.dto.InitiateMultipartUploadResult@f35d0a6]
2023-06-16 06:35:17.658 DEBUG 1 --- [tp1733581655-21] o.s.web.servlet.DispatcherServlet        : Completed 200 OK
````

As you can see, it worked on your side, but for some reason, the AWS CRT Client didn't like it.

This is the S3Mock configuration in my test:
````
    @Container
    private static final S3MockContainer s3Mock = new S3MockContainer("2.12.2")
            .withValidKmsKeys("arn:aws:kms:us-east-1:1234567890:key/valid-test-key-ref")
            .withRetainFilesOnExit(true)
            .withEnv("debug", "true");

    @DynamicPropertySource
    static void registerDynamicProperties(DynamicPropertyRegistry registry) {
        registry.add("app.props.transfers.s3.endpoint", s3Mock::getHttpEndpoint);
    }
````

This is how I create the client:
````
    @Bean
    public S3AsyncClient s3client(S3ClientConfigurationProperties s3props, AwsCredentialsProvider credentialsProvider) {
        S3CrtAsyncClientBuilder builder = S3AsyncClient.crtBuilder()
                .credentialsProvider(credentialsProvider)
                .region(s3props.getRegion())
                .forcePathStyle(true)
                .targetThroughputInGbps(20.0)
                .minimumPartSizeInBytes(8 * MB);
        if (s3props.getEndpoint() != null) {
            builder = builder.endpointOverride(s3props.getEndpoint());
        }
        return builder.build();
    }
````

If I change the implementation to the default S3AsyncClient, it works flawlessly but I lose the CRT Multipart advantages.
````
    @Bean
    public S3AsyncClient s3client(S3ClientConfigurationProperties s3props, AwsCredentialsProvider credentialsProvider) {
        S3AsyncClientBuilder builder = S3AsyncClient.builder()
                .credentialsProvider(credentialsProvider)
                .region(s3props.getRegion())
                .forcePathStyle(true);
        if (s3props.getEndpoint() != null) {
            builder = builder.endpointOverride(s3props.getEndpoint());
        }
        return builder.build();
    }
````
I have traced the error message to https://github.com/search?q=repo%3Aawslabs%2Faws-c-s3%20AWS_ERROR_S3_MISSING_UPLOAD_ID&type=code

Can you please have a look? Maybe the CRT handler is expecting something else, I don't know. 

Thanks!

**Comment by afranken** [comment]
@campidelli not sure what goes wrong with your code.
I added an integration test that uses the CRT client, and it works just fine, see linked PR...

**Comment by afranken** [comment]
there are two ways to add the CRT client to the S3AsyncClient - see `S3TestBase.kt`. It's in Kotlin, but the syntax is not too different from Java.
Not sure why, but I can't get one of the CRT clients to work with an https endpoint.
The test works with both of them.

Only the "autoCrt" client (using your way to set it up) lands in this method though:
```
		at software.amazon.awssdk.services.s3.internal.crt.S3CrtResponseHandlerAdapter.onFinished(S3CrtResponseHandlerAdapter.java:93) ~[s3-2.20.78.jar:na]
```

**Comment by campidelli** [comment]
Hi @afranken, thanks for the prompt response.

I have followed this tutorial (https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/transfer-manager.html) where they ask for this specific version or higher, I didn't know the client was part of the SDK already, good catch!

The project I am working on is similar to this, but it is an internal one.

If I change the Client to use the HTTP version, I lose the multipart upload feature< I quote from https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/crt-based-s3-client.html

> Although both components use libraries from the [AWS Common Runtime](https://docs.aws.amazon.com/sdkref/latest/guide/common-runtime.html), the AWS CRT-based S3 client uses the [aws-c-s3 library](https://github.com/awslabs/aws-c-s3) and supports the [S3 multipart upload API](https://docs.aws.amazon.com/AmazonS3/latest/userguide/mpuoverview.html) features. Since the AWS CRT-based HTTP client is meant for general purpose use, it does not support the S3 multipart upload API features.

**Comment by campidelli** [comment]
For this specific test I am using the `putObject` API, as you can check on the following code (from my REST controller):
````
    @PostMapping
    public Mono<ResponseEntity<UploadResult>> uploadHandler(@RequestHeader HttpHeaders headers, @RequestBody Flux<ByteBuffer> body) {

        long length = headers.getContentLength();
        if (length < 0) {
            throw new UploadFailedException(HttpStatus.BAD_REQUEST.value(), Optional.of("required header missing: Content-Length"));
        }

        String fileKey = UUID.randomUUID().toString();
        Map<String, String> metadata = new HashMap<>();
        metadata.put("file_name", "test");
        MediaType mediaType = headers.getContentType();

        if (mediaType == null) {
            mediaType = MediaType.APPLICATION_OCTET_STREAM;
        }

        log.info("UploadHandler: mediaType {}, length={}, fileKey = {}", mediaType, length, fileKey);
        Mono<PutObjectResponse> putObjectResponseMono = Mono.fromFuture(s3client.putObject(PutObjectRequest.builder()
                        .bucket(s3config.getBuckets().upload())
                        .contentLength(length)
                        .key(fileKey)
                        .contentType(mediaType.toString())
                        .metadata(metadata)
                        .build(),
                AsyncRequestBody.fromPublisher(body)));

        return putObjectResponseMono
                .map((response) -> {
                    checkUploadResult(response);
                    return ResponseEntity
                            .status(HttpStatus.CREATED)
                            .body(new UploadResult(HttpStatus.CREATED, new String[]{fileKey}));
                });
    }
````

**Comment by campidelli** [comment]
Can you please include this in your test and see if it works?

Thanks!

**Comment by afranken** [comment]
Just added a test, works without problems:
https://github.com/adobe/S3Mock/blob/main/integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/CrtAsyncV2IT.kt

must still be something with the way you set up the client, or the interaction with Spring reactive?
Maybe you could try to reproduce the problem in your example service...

**Comment by campidelli** [comment]
Yes, I am going to do it right now, thanks!

**Comment by campidelli** [comment]
I have updated my project and the error doesn't happen anymore.
However, I am facing another issue, which is probably an implementation error, I would gladly accept a hand here.
https://github.com/adobe/S3Mock/issues/1182
Thanks!
