### ISSUE TITLE
Service: Amazon S3; Status Code: 404; Error Code: 404

### ISSUE THREAD

**Issue by SanQi37** [adobe/S3Mock#1467]
i try to create s3mock and client to test my code,but it`s error:，
and i copy this demo：https://github.com/adobe/S3Mock/blob/2.0.7/testsupport/junit4/src/test/java/com/adobe/testing/s3mock/junit4/S3MockRuleTest.java
the exception msg is：
com.amazonaws.services.s3.model.AmazonS3Exception:  (Service: Amazon S3; Status Code: 404; Error Code: 404 ; Request ID: null; S3 Extended Request ID: null)
, S3 Extended Request ID: null
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1695)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1350)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1101)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:758)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:732)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:714)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:674)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:656)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:520)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4443)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4390)
	at com.amazonaws.services.s3.AmazonS3Client.createBucket(AmazonS3Client.java:1039)
	at com.amazonaws.services.s3.AmazonS3Client.createBucket(AmazonS3Client.java:975)....

**Comment by afranken** [comment]
With only this short error message, it's hard to say what's going on.
Probably some problem where the S3Mock is not started correctly before the test starts?
Are you sure that you copied all code?

Also, if you start a new project, I'd advise to use a Docker integration, for example [`TestContainers`](https://github.com/adobe/S3Mock#start-using-testcontainers) to start S3Mock.

**Comment by afranken** [comment]
no response for 4 weeks, closing.
