### ISSUE TITLE
Unable to upload binary file

### ISSUE THREAD

**Issue by chrissinclairedited** [adobe/S3Mock#147]
Hello,

Thanks for the project - just been trying to use it to upload files but seeing something weird:

Create a file (this seems to be the easiest way to replicate the issue), naturally my actual file isn't random:
```sh
head -c 200000 < /dev/random > /tmp/foo.txt
```

Attempt to upload the file (using python 3.7, boto3==1.9.130)
```python
import boto3
client = boto3.client("s3", "http://<my_endpoint>:9090")
client.upload_file("/tmp/foo.txt", "<bucket_name>", "foo.txt")
```

The client raises a botocore.exceptions.ClientException:
```
botocore.exceptions.ClientError: An error occurred (500) when calling the PutObject operation (reached max retries: 4): Internal Server Error
```

Tailing the logs for the S3 container sheds a bit more light:

```
s3_1        | org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.NumberFormatException: For input string: "??8?oz??@)???]'c???M?'?"
s3_1        |   at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1013) ~[spring-webmvc-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
s3_1        |   at org.springframework.web.servlet.FrameworkServlet.doPut(FrameworkServlet.java:919) ~[spring-webmvc-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
s3_1        |   at javax.servlet.http.HttpServlet.service(HttpServlet.java:668) ~[javax.servlet-api-4.0.1.jar!/:4.0.1]
s3_1        |   at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882) ~[spring-webmvc-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
s3_1        |   at javax.servlet.http.HttpServlet.service(HttpServlet.java:750) ~[javax.servlet-api-4.0.1.jar!/:4.0.1]
s3_1        |   at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:873) ~[jetty-servlet-9.4.15.v20190215.jar!/:9.4.15.v20190215]
s3_1        |   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623) ~[jetty-servlet-9.4.15.v20190215.jar!/:9.4.15.v20190215]
s3_1        |   at com.adobe.testing.s3mock.KmsValidationFilter.doFilterInternal(KmsValidationFilter.java:86) ~[classes!/:na]
s3_1        |   at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
s3_1        |   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610) ~[jetty-servlet-9.4.15.v20190215.jar!/:9.4.15.v20190215]
s3_1        |   at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) ~[spring-web-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
s3_1        |   at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
s3_1        |   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610) ~[jetty-servlet-9.4.15.v20190215.jar!/:9.4.15.v20190215]
s3_1        |   at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101) ~[spring-web-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
s3_1        |   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610) ~[jetty-servlet-9.4.15.v20190215.jar!/:9.4.15.v20190215]
s3_1        |   at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93) ~[spring-web-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
s3_1        |   at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
s3_1        |   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610) ~[jetty-servlet-9.4.15.v20190215.jar!/:9.4.15.v20190215]
s3_1        |   at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200) ~[spring-web-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
s3_1        |   at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
s3_1        |   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610) ~[jetty-servlet-9.4.15.v20190215.jar!/:9.4.15.v20190215]
s3_1        |   at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540) ~[jetty-servlet-9.4.15.v20190215.jar!/:9.4.15.v20190215]
s3_1        |   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146) ~[jetty-server-9.4.15.v20190215.jar!/:9.4.15.v20190215]
s3_1        |   at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548) ~[jetty-security-9.4.15.v20190215.jar!/:9.4.15.v20190215]
s3_1        |   at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) ~[jetty-server-9.4.15.v20190215.jar!/:9.4.15.v20190215]
s3_1        |   at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257) ~[jetty-server-9.4.15.v20190215.jar!/:9.4.15.v20190215]
s3_1        |   at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1701) ~[jetty-server-9.4.15.v20190215.jar!/:9.4.15.v20190215]
s3_1        |   at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255) ~[jetty-server-9.4.15.v20190215.jar!/:9.4.15.v20190215]
s3_1        |   at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345) ~[jetty-server-9.4.15.v20190215.jar!/:9.4.15.v20190215]
s3_1        |   at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203) ~[jetty-server-9.4.15.v20190215.jar!/:9.4.15.v20190215]
s3_1        |   at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480) ~[jetty-servlet-9.4.15.v20190215.jar!/:9.4.15.v20190215]
s3_1        |   at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1668) ~[jetty-server-9.4.15.v20190215.jar!/:9.4.15.v20190215]
s3_1        |   at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201) ~[jetty-server-9.4.15.v20190215.jar!/:9.4.15.v20190215]
s3_1        |   at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247) ~[jetty-server-9.4.15.v20190215.jar!/:9.4.15.v20190215]
s3_1        |   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144) ~[jetty-server-9.4.15.v20190215.jar!/:9.4.15.v20190215]
s3_1        |   at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) ~[jetty-server-9.4.15.v20190215.jar!/:9.4.15.v20190215]
s3_1        |   at org.eclipse.jetty.server.Server.handle(Server.java:502) ~[jetty-server-9.4.15.v20190215.jar!/:9.4.15.v20190215]
s3_1        |   at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370) ~[jetty-server-9.4.15.v20190215.jar!/:9.4.15.v20190215]
s3_1        |   at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267) ~[jetty-server-9.4.15.v20190215.jar!/:9.4.15.v20190215]
s3_1        |   at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305) ~[jetty-io-9.4.15.v20190215.jar!/:9.4.15.v20190215]
s3_1        |   at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) ~[jetty-io-9.4.15.v20190215.jar!/:9.4.15.v20190215]
s3_1        |   at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117) ~[jetty-io-9.4.15.v20190215.jar!/:9.4.15.v20190215]
s3_1        |   at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333) ~[jetty-util-9.4.15.v20190215.jar!/:9.4.15.v20190215]
s3_1        |   at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310) ~[jetty-util-9.4.15.v20190215.jar!/:9.4.15.v20190215]
s3_1        |   at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168) ~[jetty-util-9.4.15.v20190215.jar!/:9.4.15.v20190215]
s3_1        |   at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126) ~[jetty-util-9.4.15.v20190215.jar!/:9.4.15.v20190215]
s3_1        |   at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366) ~[jetty-util-9.4.15.v20190215.jar!/:9.4.15.v20190215]
s3_1        |   at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765) ~[jetty-util-9.4.15.v20190215.jar!/:9.4.15.v20190215]
s3_1        |   at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683) ~[jetty-util-9.4.15.v20190215.jar!/:9.4.15.v20190215]
s3_1        |   at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
s3_1        | Caused by: java.lang.NumberFormatException: For input string: "??8?oz??@)???]'c???M?'?"
s3_1        |   at java.base/java.lang.NumberFormatException.forInputString(Unknown Source) ~[na:na]
s3_1        |   at java.base/java.lang.Integer.parseInt(Unknown Source) ~[na:na]
s3_1        |   at com.adobe.testing.s3mock.util.AwsChunkDecodingInputStream.read(AwsChunkDecodingInputStream.java:79) ~[classes!/:na]
s3_1        |   at java.base/java.io.InputStream.read(Unknown Source) ~[na:na]
s3_1        |   at java.base/java.io.InputStream.read(Unknown Source) ~[na:na]
s3_1        |   at com.adobe.testing.s3mock.domain.FileStore.inputStreamToFile(FileStore.java:437) ~[classes!/:na]
s3_1        |   at com.adobe.testing.s3mock.domain.FileStore.putS3Object(FileStore.java:248) ~[classes!/:na]
s3_1        |   at com.adobe.testing.s3mock.FileStoreController.putObject(FileStoreController.java:476) ~[classes!/:na]
s3_1        |   at jdk.internal.reflect.GeneratedMethodAccessor26.invoke(Unknown Source) ~[na:na]
s3_1        |   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
s3_1        |   at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
s3_1        |   at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189) ~[spring-web-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
s3_1        |   at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
s3_1        |   at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) ~[spring-webmvc-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
s3_1        |   at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892) ~[spring-webmvc-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
s3_1        |   at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[spring-webmvc-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
s3_1        |   at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
s3_1        |   at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038) ~[spring-webmvc-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
s3_1        |   at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942) ~[spring-webmvc-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
s3_1        |   at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005) ~[spring-webmvc-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
s3_1        |   ... 49 common frames omitted
```

Looks like the upload handler is assuming that it's going to be given a multipart upload where the content-length is given before a semi-colon (in hex format?) but we're not passing a hex string there - instead it looks to be something like `??8?oz??@)???]'c???M?'?` (https://github.com/adobe/S3Mock/blob/master/server/src/main/java/com/adobe/testing/s3mock/util/AwsChunkDecodingInputStream.java#L79).

I wondered if this was a boto3 issue / my error but the exact same code works against the live S3 API (just removing the `endpoint_url` when creating the client). Any ideas?

**Comment by resilva87** [comment]
Hi,

I got the exact same error while trying to upload a binary (JPEG image) file. Any thoughts or update about this issue?

**Comment by chrissinclairedited** [comment]
Hey @resilva87 - not sure if it'll work for you but I gave up in the end and have been using https://hub.docker.com/r/andrewgaul/s3proxy/ successfully since.

**Comment by agudian** [comment]
After investigating with a small reproducer, we finally figured out what boto3 did differently compared to how we used the S3 Java SDK in our tests.
It's the same issue as reported in #121, so I'll close this here. The fix is already on the way, though.
