### ISSUE TITLE
while reading large number of record from s3mock getting Exception( java.io.IOException: Attempted read on closed stream)

### ISSUE THREAD

**Issue by soumya-222** [adobe/S3Mock#1514]
pushed 100million record to the s3mock which is  200 csv files 
while reading the files after reading around 40lakh records gettingException caused by  **java.io.IOException: Attempted read on closed stream**

below is the stack trace 

2023-12-04 19:00:20.628 ERROR [System   ] [pool-8-thread-1] c.m.h.s.collect.source.aws.AwsCURSource : file load failed for tenant [397929655]
com.microfocus.hcm.showback.collect.CollectionException: failed to download S3 object
        at com.microfocus.hcm.showback.collect.aws.manifest.AwsS3ObjectService.downloadS3ObjectWithRetry(AwsS3ObjectService.java:76)
        at com.microfocus.hcm.showback.collect.aws.manifest.AwsS3ObjectService.downloadS3Object(AwsS3ObjectService.java:126)
        at com.microfocus.hcm.showback.collect.aws.AwsRealReportBucketService.loadReport(AwsRealReportBucketService.java:114)
        at com.microfocus.hcm.showback.collect.source.aws.AwsCURSource.loadFile(AwsCURSource.java:462)
        at com.microfocus.hcm.showback.collect.source.aws.AwsCURSource.lambda$loadManifestFilesConcurrently$1(AwsCURSource.java:424)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.io.IOException: Attempted read on closed stream.
        at org.apache.http.conn.EofSensorInputStream.isReadAllowed(EofSensorInputStream.java:107)
        at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:133)
        at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
        at com.amazonaws.event.ProgressInputStream.read(ProgressInputStream.java:180)
        at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
        at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
        at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
        at com.amazonaws.event.ProgressInputStream.read(ProgressInputStream.java:180)
        at java.base/java.security.DigestInputStream.read(DigestInputStream.java:162)
        at com.amazonaws.services.s3.internal.DigestValidationInputStream.read(DigestValidationInputStream.java:59)
        at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
        at com.amazonaws.services.s3.internal.S3AbortableInputStream.read(S3AbortableInputStream.java:125)
        at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
        at java.base/java.io.FilterInputStream.read(FilterInputStream.java:106)
        at com.microfocus.hcm.showback.collect.aws.manifest.AwsS3ObjectService.loadS3ObjectToLocalFile(AwsS3ObjectService.java:102)
        at com.microfocus.hcm.showback.collect.aws.manifest.AwsS3ObjectService.downloadS3ObjectWithRetry(AwsS3ObjectService.java:72)
        ... 8 common frames omitted
2023-12-04 19:00:20.635 WARN  [System   ] [pool-8-thread-1] c.m.h.s.collect.SourceSinkCollector : error during sink stream batch for tenant [397929655], rolling back
com.microfocus.hcm.showback.collect.CollectionException: failed to download S3 object
        at com.microfocus.hcm.showback.collect.aws.manifest.AwsS3ObjectService.downloadS3ObjectWithRetry(AwsS3ObjectService.java:76)
        at com.microfocus.hcm.showback.collect.aws.manifest.AwsS3ObjectService.downloadS3Object(AwsS3ObjectService.java:126)
        at com.microfocus.hcm.showback.collect.aws.AwsRealReportBucketService.loadReport(AwsRealReportBucketService.java:114)
        at com.microfocus.hcm.showback.collect.source.aws.AwsCURSource.loadFile(AwsCURSource.java:462)
        at com.microfocus.hcm.showback.collect.source.aws.AwsCURSource.lambda$loadManifestFilesConcurrently$1(AwsCURSource.java:424)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.io.IOException: Attempted read on closed stream.
        at org.apache.http.conn.EofSensorInputStream.isReadAllowed(EofSensorInputStream.java:107)
        at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:133)
        at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
        at com.amazonaws.event.ProgressInputStream.read(ProgressInputStream.java:180)
        at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
        at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
        at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
        at com.amazonaws.event.ProgressInputStream.read(ProgressInputStream.java:180)
        at java.base/java.security.DigestInputStream.read(DigestInputStream.java:162)
        at com.amazonaws.services.s3.internal.DigestValidationInputStream.read(DigestValidationInputStream.java:59)
        at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
        at com.amazonaws.services.s3.internal.S3AbortableInputStream.read(S3AbortableInputStream.java:125)
        at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
        at java.base/java.io.FilterInputStream.read(FilterInputStream.java:106)
        at com.microfocus.hcm.showback.collect.aws.manifest.AwsS3ObjectService.loadS3ObjectToLocalFile(AwsS3ObjectService.java:102)
        at com.microfocus.hcm.showback.collect.aws.manifest.AwsS3ObjectService.downloadS3ObjectWithRetry(AwsS3ObjectService.java:72)
        ... 8 common frames omitted
2023-12-04 19:00:20.638 INFO  [System   ] [pool-8-thread-1] c.m.h.s.c.sink.stream.CopyStreamSink : copyStream rolled back and cleaned up
2023-12-04 19:00:21.161 ERROR [System   ] [pool-8-thread-4] c.m.h.s.collect.source.aws.AwsCURSource : Failure in other thread
com.microfocus.hcm.showback.collect.CollectionException: failed to download S3 object
        at com.microfocus.hcm.showback.collect.aws.manifest.AwsS3ObjectService.downloadS3ObjectWithRetry(AwsS3ObjectService.java:76)
        at com.microfocus.hcm.showback.collect.aws.manifest.AwsS3ObjectService.downloadS3Object(AwsS3ObjectService.java:126)
        at com.microfocus.hcm.showback.collect.aws.AwsRealReportBucketService.loadReport(AwsRealReportBucketService.java:114)
        at com.microfocus.hcm.showback.collect.source.aws.AwsCURSource.loadFile(AwsCURSource.java:462)
        at com.microfocus.hcm.showback.collect.source.aws.AwsCURSource.lambda$loadManifestFilesConcurrently$1(AwsCURSource.java:424)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.io.IOException: Attempted read on closed stream.
        at org.apache.http.conn.EofSensorInputStream.isReadAllowed(EofSensorInputStream.java:107)
        at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:133)
        at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
        at com.amazonaws.event.ProgressInputStream.read(ProgressInputStream.java:180)
        at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
        at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
        at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
        at com.amazonaws.event.ProgressInputStream.read(ProgressInputStream.java:180)
        at java.base/java.security.DigestInputStream.read(DigestInputStream.java:162)
        at com.amazonaws.services.s3.internal.DigestValidationInputStream.read(DigestValidationInputStream.java:59)
        at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
        at com.amazonaws.services.s3.internal.S3AbortableInputStream.read(S3AbortableInputStream.java:125)
        at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
        at java.base/java.io.FilterInputStream.read(FilterInputStream.java:106)
        at com.microfocus.hcm.showback.collect.aws.manifest.AwsS3ObjectService.loadS3ObjectToLocalFile(AwsS3ObjectService.java:102)
        at com.microfocus.hcm.showback.collect.aws.manifest.AwsS3ObjectService.downloadS3ObjectWithRetry(AwsS3ObjectService.java:72)
        ... 8 common frames omitted
2023-12-04 19:00:21.180 ERROR [System   ] [pool-8-thread-4] c.m.h.s.collect.source.aws.AwsCURSource : file load failed for tenant [397929655]
com.microfocus.boost.core.error.BoostException: com.microfocus.hcm.showback.collect.CollectionException: failed to download S3 object
        at com.microfocus.hcm.showback.collect.source.aws.AwsCURSource.lambda$loadFile$4(AwsCURSource.java:465)
        at com.microfocus.hcm.showback.collect.aws.AwsBaseReportBucketService.loadCsv(AwsBaseReportBucketService.java:86)
        at com.microfocus.hcm.showback.collect.aws.AwsRealReportBucketService.loadReport(AwsRealReportBucketService.java:119)
        at com.microfocus.hcm.showback.collect.source.aws.AwsCURSource.loadFile(AwsCURSource.java:462)
        at com.microfocus.hcm.showback.collect.source.aws.AwsCURSource.lambda$loadManifestFilesConcurrently$1(AwsCURSource.java:424)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.microfocus.hcm.showback.collect.CollectionException: failed to download S3 object
        at com.microfocus.hcm.showback.collect.aws.manifest.AwsS3ObjectService.downloadS3ObjectWithRetry(AwsS3ObjectService.java:76)
        at com.microfocus.hcm.showback.collect.aws.manifest.AwsS3ObjectService.downloadS3Object(AwsS3ObjectService.java:126)
        at com.microfocus.hcm.showback.collect.aws.AwsRealReportBucketService.loadReport(AwsRealReportBucketService.java:114)
        ... 6 common frames omitted
Caused by: java.io.IOException: Attempted read on closed stream.
        at org.apache.http.conn.EofSensorInputStream.isReadAllowed(EofSensorInputStream.java:107)
        at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:133)
        at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
        at com.amazonaws.event.ProgressInputStream.read(ProgressInputStream.java:180)
        at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
        at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
        at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
        at com.amazonaws.event.ProgressInputStream.read(ProgressInputStream.java:180)
        at java.base/java.security.DigestInputStream.read(DigestInputStream.java:162)
        at com.amazonaws.services.s3.internal.DigestValidationInputStream.read(DigestValidationInputStream.java:59)
        at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
        at com.amazonaws.services.s3.internal.S3AbortableInputStream.read(S3AbortableInputStream.java:125)
        at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
        at java.base/java.io.FilterInputStream.read(FilterInputStream.java:106)
        at com.microfocus.hcm.showback.collect.aws.manifest.AwsS3ObjectService.loadS3ObjectToLocalFile(AwsS3ObjectService.java:102)
        at com.microfocus.hcm.showback.collect.aws.manifest.AwsS3ObjectService.downloadS3ObjectWithRetry(AwsS3ObjectService.java:72)
        ... 8 common frames omitted

**Comment by afranken** [comment]
@soumya-222 
you persisted 100mio records in S3Mock?
I'm guessing that the internal data structures won't support so many records...
We persist metadata in files, where references of all keys in a bucket are written into one file. 

This is a utility meant for testing locally.

**Comment by afranken** [comment]
no answer within a month. Closing this issue.
If there are further questions please reopen or open a new issue.
