### ISSUE TITLE
LoggerFactory is not a Logback LoggerContext but Logback is on the classpath

### ISSUE THREAD

**Issue by castioussupreme** [adobe/S3Mock#209]
Can't use any of it due to logger mismatch.  Similar to:
https://github.com/adobe/S3Mock/issues/141
But the explanation is not clear in "exclude the former two depdendencies from the s3mock dependency that you reference." If I remove the dependencies from the build would it not fail to build?

Import for my log solution:

java_library(
    name = "slf4j_api",
    visibility = ["//visibility:public"],
    exports = [
        "@org_slf4j_slf4j_api//jar",
    ],
)

import for the s3mock:

java_library(
    name = "s3mock_junit5",
    visibility = ["//visibility:public"],
    exports = [
        "@com_adobe_testing_s3mock_junit5//jar",
    ],
    runtime_deps = [
        "@ch_qos_logback_logback_classic//jar",
        "@ch_qos_logback_logback_core//jar",
        "@com_adobe_testing_s3mock//jar",
        "@com_adobe_testing_s3mock_testsupport_common//jar",
        "@com_amazonaws_aws_java_sdk_core//jar",
        "@com_amazonaws_aws_java_sdk_kms//jar",
        "@com_amazonaws_aws_java_sdk_s3//jar",
        "@com_amazonaws_jmespath_java//jar",
        "@com_fasterxml_classmate//jar",
        "@com_fasterxml_jackson_core_jackson_annotations//jar",
        "@com_fasterxml_jackson_core_jackson_core//jar",
        "@com_fasterxml_jackson_core_jackson_databind//jar",
        "@com_fasterxml_jackson_dataformat_jackson_dataformat_cbor//jar",
        "@com_fasterxml_jackson_dataformat_jackson_dataformat_xml//jar",
        "@com_fasterxml_jackson_datatype_jackson_datatype_jdk8//jar",
        "@com_fasterxml_jackson_datatype_jackson_datatype_jsr310//jar",
        "@com_fasterxml_jackson_module_jackson_module_jaxb_annotations//jar",
        "@com_fasterxml_jackson_module_jackson_module_parameter_names//jar",
        "@com_fasterxml_woodstox_woodstox_core//jar",
        "@com_typesafe_netty_netty_reactive_streams//jar",
        "@com_typesafe_netty_netty_reactive_streams_http//jar",
        "@commons_codec_commons_codec//jar",
        "@commons_io_commons_io//jar",
        "@commons_logging_commons_logging//jar",
        "@io_netty_netty_buffer//jar",
        "@io_netty_netty_codec//jar",
        "@io_netty_netty_codec_http//jar",
        "@io_netty_netty_codec_http2//jar",
        "@io_netty_netty_common//jar",
        "@io_netty_netty_handler//jar",
        "@io_netty_netty_resolver//jar",
        "@io_netty_netty_transport//jar",
        "@io_netty_netty_transport_native_epoll//jar",
        "@io_netty_netty_transport_native_unix_common//jar",
        "@javax_annotation_javax_annotation_api//jar",
        "@javax_servlet_javax_servlet_api//jar",
        "@javax_validation_validation_api//jar",
        "@joda_time_joda_time//jar",
        "@org_apache_commons_commons_lang3//jar",
        "@org_apache_httpcomponents_httpclient//jar",
        "@org_apache_httpcomponents_httpcore//jar",
        "@org_apache_logging_log4j_log4j_api//jar",
        "@org_apache_logging_log4j_log4j_to_slf4j//jar",
        "@org_apiguardian_apiguardian_api//jar",
        "@org_codehaus_woodstox_stax2_api//jar",
        "@org_eclipse_jetty_jetty_continuation//jar",
        "@org_eclipse_jetty_jetty_http//jar",
        "@org_eclipse_jetty_jetty_io//jar",
        "@org_eclipse_jetty_jetty_security//jar",
        "@org_eclipse_jetty_jetty_server//jar",
        "@org_eclipse_jetty_jetty_servlet//jar",
        "@org_eclipse_jetty_jetty_servlets//jar",
        "@org_eclipse_jetty_jetty_util//jar",
        "@org_eclipse_jetty_jetty_webapp//jar",
        "@org_eclipse_jetty_jetty_xml//jar",
        "@org_hibernate_validator_hibernate_validator//jar",
        "@org_jboss_logging_jboss_logging//jar",
        "@org_junit_jupiter_junit_jupiter_api//jar",
        "@org_junit_platform_junit_platform_commons//jar",
        "@org_mortbay_jasper_apache_el//jar",
        "@org_opentest4j_opentest4j//jar",
        "@org_reactivestreams_reactive_streams//jar",
        "@org_slf4j_jul_to_slf4j//jar",
        "@org_slf4j_slf4j_api//jar",
        "@org_springframework_boot_spring_boot//jar",
        "@org_springframework_boot_spring_boot_autoconfigure//jar",
        "@org_springframework_boot_spring_boot_starter//jar",
        "@org_springframework_boot_spring_boot_starter_jetty//jar",
        "@org_springframework_boot_spring_boot_starter_json//jar",
        "@org_springframework_boot_spring_boot_starter_logging//jar",
        "@org_springframework_boot_spring_boot_starter_web//jar",
        "@org_springframework_spring_aop//jar",
        "@org_springframework_spring_beans//jar",
        "@org_springframework_spring_context//jar",
        "@org_springframework_spring_core//jar",
        "@org_springframework_spring_expression//jar",
        "@org_springframework_spring_jcl//jar",
        "@org_springframework_spring_web//jar",
        "@org_springframework_spring_webmvc//jar",
        "@org_yaml_snakeyaml//jar",
        "@software_amazon_awssdk_annotations//jar",
        "@software_amazon_awssdk_apache_client//jar",
        "@software_amazon_awssdk_auth//jar",
        "@software_amazon_awssdk_aws_core//jar",
        "@software_amazon_awssdk_aws_query_protocol//jar",
        "@software_amazon_awssdk_aws_xml_protocol//jar",
        "@software_amazon_awssdk_http_client_spi//jar",
        "@software_amazon_awssdk_netty_nio_client//jar",
        "@software_amazon_awssdk_profiles//jar",
        "@software_amazon_awssdk_protocol_core//jar",
        "@software_amazon_awssdk_regions//jar",
        "@software_amazon_awssdk_s3//jar",
        "@software_amazon_awssdk_sdk_core//jar",
        "@software_amazon_awssdk_url_connection_client//jar",
        "@software_amazon_awssdk_utils//jar",
        "@software_amazon_eventstream_eventstream//jar",
        "@software_amazon_ion_ion_java//jar",
    ],
)

Usage:

  @RegisterExtension
  public static S3MockExtension S3_MOCK = S3MockExtension.builder().build();
  private final AmazonS3 s3Client = S3_MOCK.createS3Client();

Log out:

java.lang.IllegalArgumentException: LoggerFactory is not a Logback LoggerContext but Logback is on the classpath. Either remove Logback or the competing implementation (class org.slf4j.impl.JDK14LoggerFactory loaded from [OMMITED]). If you are using WebLogic you will need to add 'org.slf4j' to prefer-application-packages in WEB-INF/weblogic.xml: org.slf4j.impl.JDK14LoggerFactory

	at org.springframework.util.Assert.instanceCheckFailed(Assert.java:655)
	at org.springframework.util.Assert.isInstanceOf(Assert.java:555)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.getLoggerContext(LogbackLoggingSystem.java:280)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.beforeInitialize(LogbackLoggingSystem.java:104)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationStartingEvent(LoggingApplicationListener.java:219)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:200)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.boot.context.event.EventPublishingRunListener.starting(EventPublishingRunListener.java:70)
	at org.springframework.boot.SpringApplicationRunListeners.starting(SpringApplicationRunListeners.java:47)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:302)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:140)
	at com.adobe.testing.s3mock.S3MockApplication.start(S3MockApplication.java:181)
	at com.adobe.testing.s3mock.testsupport.common.S3MockStarter.start(S3MockStarter.java:167)
	at com.adobe.testing.s3mock.junit5.S3MockExtension.startOnlySingleInstance(S3MockExtension.java:133)
	at com.adobe.testing.s3mock.junit5.S3MockExtension.beforeAll(S3MockExtension.java:85)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.lambda$invokeBeforeAllCallbacks$8(ClassTestDescriptor.java:361)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.invokeBeforeAllCallbacks(ClassTestDescriptor.java:361)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.before(ClassTestDescriptor.java:197)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.before(ClassTestDescriptor.java:77)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:132)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:197)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:191)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
	Suppressed: java.lang.NullPointerException
		at com.adobe.testing.s3mock.testsupport.common.S3MockStarter.stop(S3MockStarter.java:171)
		at com.adobe.testing.s3mock.junit5.S3MockExtension.stopWhenLastConsumerFinished(S3MockExtension.java:127)
		at com.adobe.testing.s3mock.junit5.S3MockExtension.afterAll(S3MockExtension.java:90)
		at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.lambda$invokeAfterAllCallbacks$12(ClassTestDescriptor.java:399)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
		at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.lambda$invokeAfterAllCallbacks$13(ClassTestDescriptor.java:399)
		at java.util.ArrayList.forEach(ArrayList.java:1257)
		at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.invokeAfterAllCallbacks(ClassTestDescriptor.java:399)
		at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.after(ClassTestDescriptor.java:221)
		at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.after(ClassTestDescriptor.java:77)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:145)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:145)
		... 27 more

**Comment by afranken** [comment]
S3Mock 2.2.0 was just released that now includes support for [TestContainers](https://www.testcontainers.org/).
If there is a possibility of running Docker during your build, I would highly suggest migrating to TestContainers.

Using S3MockApplication directly or through one of the unit test modules will always have the risk of breaking because of dependencies that are pulled in by the application that is being tested, and auto configration that is added through Spring Boot updates in the S3Mock.

Using Docker in your tests will insulate both applications dependencies and application life cycles.
