### ISSUE TITLE
NoSuchMethodError when running S3 Mock in Java 8

### ISSUE THREAD

**Issue by HackerTheMonkey** [adobe/S3Mock#243]
Hi there,

I am building a service that uses SpringBoot version `2.3.3` and java 8 which uses S3 Mock with Junit5 tests. 

The version of S3 Mock that I am using is `2.1.26` which seems to have been built with a version higher than Java 8 if I got this right, which is causing the following exception to be thrown for me while trying to do something like this:

_this is what I am trying to do_
```
PutObjectRequest request = PutObjectRequest.builder()
                .bucket("blah")
                .key("foo/ab/cd/foo.json")
                .build();
        createClient().putObject(request, RequestBody.fromBytes(Base64.getEncoder().encode(UUID.randomUUID().toString().getBytes())));
```
_and this is what I am getting_
```
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1055)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPut(FrameworkServlet.java:920)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:520)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:584)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1651)
	at com.adobe.testing.s3mock.KmsValidationFilter.doFilterInternal(KmsValidationFilter.java:91)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1638)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1638)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:103)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1638)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1638)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1638)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:567)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1610)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1377)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:507)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1580)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1292)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:501)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:135)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
	at com.adobe.testing.s3mock.util.AwsChunkDecodingInputStream.readUntil(AwsChunkDecodingInputStream.java:108)
	at com.adobe.testing.s3mock.util.AwsChunkDecodingInputStream.read(AwsChunkDecodingInputStream.java:74)
	at java.io.InputStream.read(InputStream.java:170)
	at java.io.InputStream.read(InputStream.java:101)
	at com.adobe.testing.s3mock.domain.FileStore.inputStreamToFile(FileStore.java:445)
	at com.adobe.testing.s3mock.domain.FileStore.putS3Object(FileStore.java:255)
	at com.adobe.testing.s3mock.FileStoreController.putObject(FileStoreController.java:517)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
```

I believe this has to do with the fact that from Java 9 onward the `java.nio.ByteBuffer.clear` returns a `java.nio.ByteBuffer` as opposed to `Buffer` in Java 8. 

Can someone please shed some light on this if this is a genuine issue or if I have got something incorrectly?

UPDATE:

Running `file` against the class that causing the above exception gives me the following, which contradicts my intial guess

```
com/adobe/testing/s3mock/util/AwsChunkDecodingInputStream.class: compiled Java class data, version 52.0 (Java 1.8)
```

**Comment by afranken** [comment]
Hi!
We're using Java 8 to compile all classes here:
https://github.com/adobe/S3Mock/blob/main/pom.xml#L51

When I copy and paste your code into a new test method into one of the Unit-Test classes in this repository, it executes fine with Java8, for example:
https://github.com/adobe/S3Mock/blob/main/testsupport/junit5/src/test/java/com/adobe/testing/s3mock/junit5/sdk2/S3MockExtensionProgrammaticTest.java

I can only guess that you're accidentally using Java 9+ to execute.

**Comment by HackerTheMonkey** [comment]
Thanks for looking into it. 

I've tried it on a different machine that has nothing else but Java 8 and had the same error. I've tried as well to print out the JRE version prior to invoking that as in below:

```
![image](https://user-images.githubusercontent.com/776139/92398059-c59e7d80-f11f-11ea-93a8-d4d3a86874e8.png)
```

I will try to build and run within a docker container with java 8 and see what might be happening.

**Comment by afranken** [comment]
just created this out of curiosity, works out-of-the-box for me:
https://github.com/afranken/S3Mock-SpringBoot-junit5

Just went to https://start.spring.io/ and selected Java8, added S3Mock.

**Comment by HackerTheMonkey** [comment]
Appreciate looking further into it.

I had a bit more time this evening and thought of running some tests.

I created the following class locally and then inspected its bytecode, it simply calls the `clear` method on `ByteBuffer` just like `AwsChunkDecodingInputStream`

_the test code_
```
public static void testit(){
		final ByteBuffer byteBuffer = ByteBuffer.allocate(1);
		byteBuffer.clear();
}
```

_the outcome of javap against the compiled bytecode with Java8 on macOSX_

```
javap -p -c -l -s -constants Foo.class


public static void test_it();
    descriptor: ()V
    Code:
       0: iconst_1
       1: invokestatic  #22                 // Method java/nio/ByteBuffer.allocate:(I)Ljava/nio/ByteBuffer;
       4: astore_0
       5: aload_0
       6: invokevirtual #23                 // Method java/nio/ByteBuffer.clear:()Ljava/nio/Buffer;
       9: pop
      10: return
    LineNumberTable:
      line 123: 0
      line 124: 5
      line 125: 10
    LocalVariableTable:
      Start  Length  Slot  Name   Signature
          5       6     0 byteBuffer   Ljava/nio/ByteBuffer;
```

Note that the `clear` method return type is compiled as `java.nio.Buffer`

Now, I tried to do the same against your jar downloaded from maven central both on Mac and Linux via Java 8, and here's what I get:

```
private byte[] readUntil(byte[]) throws java.io.IOException;
    descriptor: ([B)[B
    Code:
       0: aload_0
       1: getfield      #6                  // Field byteBuffer:Ljava/nio/ByteBuffer;
       4: invokevirtual #18                 // Method java/nio/ByteBuffer.clear:()Ljava/nio/ByteBuffer;
       7: pop
       8: aload_0
       9: aload_0
      10: getfield      #6                  // Field byteBuffer:Ljava/nio/ByteBuffer;
      13: invokevirtual #19                 // Method java/nio/ByteBuffer.asReadOnlyBuffer:()Ljava/nio/ByteBuffer;
      16: aload_1
      17: invokespecial #20                 // Method endsWith:(Ljava/nio/ByteBuffer;[B)Z
      20: ifne          56
      23: aload_0
      24: getfield      #7                  // Field source:Ljava/io/InputStream;
      27: invokevirtual #16                 // Method java/io/InputStream.read:()I
```

You can clearly see above that the `clear` method return type is `java.nio.ByteBuffer` despite the fact that the magic number on the class is 52 which means it was in fact compiled with Java8. 


Personally, I am not sure what caused that but it explains the exception that I get since in Java 9 the `clear` method returns `java.nio.ByteBuffer` as opposed to `java.nio.Buffer`

**Comment by HackerTheMonkey** [comment]
Right, I found what the problem is. 

The releases of the S3 Mock is compiled with Java 11, using the `source` and `target` compiler argument set to 8, these arguments have been deprecated in favour of `--release` as they seem to leak JDK9+ dependencies into a java8 source and target build. 

I have checked out your code and built it from source using:

1- When built as-is with java8, I get the following outcome:

```
private byte[] readUntil(byte[]) throws java.io.IOException;
    descriptor: ([B)[B
    Code:
       0: aload_0
       1: getfield      #6                  // Field byteBuffer:Ljava/nio/ByteBuffer;
       4: invokevirtual #18                 // Method java/nio/ByteBuffer.clear:()Ljava/nio/Buffer;
       7: pop
       8: aload_0
       9: aload_0
      10: getfield      #6                  // Field byteBuffer:Ljava/nio/ByteBuffer;
      13: invokevirtual #19                 // Method java/nio/ByteBuffer.asReadOnlyBuffer:()Ljava/nio/ByteBuffer;
      16: aload_1
      17: invokespecial #20                 // Method endsWith:(Ljava/nio/ByteBuffer;[B)Z
      20: ifne          56
      23: aload_0
      24: getfield      #7                  // Field source:Ljava/io/InputStream;
      27: invokevirtual #16                 // Method java/io/InputStream.read:()I
```

which is what one would expect 

2- When building it as is with Java 11, I get the following which is exactly what I get when using the pre-built jar downloaded from maven central

```
private byte[] readUntil(byte[]) throws java.io.IOException;
    descriptor: ([B)[B
    Code:
       0: aload_0
       1: getfield      #6                  // Field byteBuffer:Ljava/nio/ByteBuffer;
       4: invokevirtual #18                 // Method java/nio/ByteBuffer.clear:()Ljava/nio/ByteBuffer;
       7: pop
       8: aload_0
       9: aload_0
      10: getfield      #6                  // Field byteBuffer:Ljava/nio/ByteBuffer;
      13: invokevirtual #19                 // Method java/nio/ByteBuffer.asReadOnlyBuffer:()Ljava/nio/ByteBuffer;
      16: aload_1
      17: invokespecial #20                 // Method endsWith:(Ljava/nio/ByteBuffer;[B)Z
      20: ifne          56
      23: aload_0
      24: getfield      #7                  // Field source:Ljava/io/InputStream;
      27: invokevirtual #16                 // Method java/io/InputStream.read:()I
```

3- Now, to prove that the above is right, I have changed the pom section in the following manner and rebuilt:

_before_
```
<plugin>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.8.1</version>
          <configuration>
            <source>${java.version}</source>
            <target>${java.version}</target>
            <encoding>${project.build.sourceEncoding}</encoding>
          </configuration>
 </plugin>
```

_after_

```
<plugin>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.8.1</version>
          <configuration>
		        <release>8</release>
            <encoding>${project.build.sourceEncoding}</encoding>
          </configuration>
        </plugin>
```

And voila, now I get the expected outcome:

```
private byte[] readUntil(byte[]) throws java.io.IOException;
    descriptor: ([B)[B
    Code:
       0: aload_0
       1: getfield      #6                  // Field byteBuffer:Ljava/nio/ByteBuffer;
       4: invokevirtual #18                 // Method java/nio/ByteBuffer.clear:()Ljava/nio/Buffer;
       7: pop
       8: aload_0
       9: aload_0
      10: getfield      #6                  // Field byteBuffer:Ljava/nio/ByteBuffer;
      13: invokevirtual #19                 // Method java/nio/ByteBuffer.asReadOnlyBuffer:()Ljava/nio/ByteBuffer;
      16: aload_1
      17: invokespecial #20                 // Method endsWith:(Ljava/nio/ByteBuffer;[B)Z
      20: ifne          56
      23: aload_0
      24: getfield      #7                  // Field source:Ljava/io/InputStream;
      27: invokevirtual #16                 // Method java/io/InputStream.read:()I
```

Happy to submit a PR if you guys are OK with the above


cheers

**Comment by HackerTheMonkey** [comment]
@afranken What do you think? I guess an alternative to the above would be to not change the code but build with Java8 instead.

**Comment by afranken** [comment]
@HackerTheMonkey sry for the delay - was swamped at work.
I just created a PR, will try to get @agudian to review and merge tomorrow and then release a new version. :)

Going back to JDK8 may have been an option, but problematic since only a few companies are still supporting JDK8 with security fixes for a subscription fee and I'm not sure if the Github build infrastructure we're now using is offering a JDK8 distribution that still receives those fixes.

**Comment by afranken** [comment]
Still wondering why the old version works for me... 
I have JDK8, JDK11 and the newest JDK installed on my machine - there's probably some magic going on that pulls in the correct `rt.jar` if it's present in the system?

**Comment by agudian** [comment]
Great analysis, @HackerTheMonkey! The release with the suggested fix is out, please give it a try.

**Comment by HackerTheMonkey** [comment]
thanks guys for the quick response, much appreciated 🙌 🙏 

I've used the new release and works great.

cheers

**Comment by HackerTheMonkey** [comment]
> Still wondering why the old version works for me...
> I have JDK8, JDK11 and the newest JDK installed on my machine - there's probably some magic going on that pulls in the correct `rt.jar` if it's present in the system?

yeah, that's strange indeed. One thing you could try to see if there's in fact some weirdness _somwhere else_

1- Create a simple class like this:
```
public class Foo{
      public static void main(String args[]){
            final ByteBuffer byteBuffer = ByteBuffer.allocate(1);
	    byteBuffer.clear();
     }
}
```

- compile this class with Java 9+, using `source` and `target` to `1.8`
- run this class with JRE 8 and then JRE 9 or 11 and see the difference
