### ISSUE TITLE
Consul Auto Config Causes Failure

### ISSUE THREAD

**Issue by ateebkhawaja** [adobe/S3Mock#61]
Hello Everyone. I am back again with another bug.

I am facing a similar issue as with the Security Auto Config. The project included Consul as a key/value store. When the following dependency is included, the app tries to connect to consul even in JUnits, which causes a failure. While the service does use Consul, JUnits should not be reliant on the service being up or down.

Parent:
```
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.0.1.RELEASE</version>
	</parent>
```

Dependency:
```
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-consul-config</artifactId>
			<version>2.0.0.RC1</version>
		</dependency>
		<dependency>
			<groupId>com.adobe.testing</groupId>
			<artifactId>s3mock-junit4</artifactId>
			<version>2.0.3</version>
			<scope>test</scope>
		</dependency>
```

Exception:
```
com.ecwid.consul.v1.OperationException: OperationException(statusCode=503, statusMessage='Service Unavailable: Back-end server is at capacity', statusContent='')
	at com.ecwid.consul.v1.kv.KeyValueConsulClient.getKVValues(KeyValueConsulClient.java:159)
	at com.ecwid.consul.v1.ConsulClient.getKVValues(ConsulClient.java:534)
	at org.springframework.cloud.consul.config.ConsulPropertySource.init(ConsulPropertySource.java:66)
	at org.springframework.cloud.consul.config.ConsulPropertySourceLocator.create(ConsulPropertySourceLocator.java:166)
	at org.springframework.cloud.consul.config.ConsulPropertySourceLocator.locate(ConsulPropertySourceLocator.java:132)
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:94)
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:633)
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:373)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:325)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:137)
	at com.adobe.testing.s3mock.S3MockApplication.start(S3MockApplication.java:177)
	at com.adobe.testing.s3mock.testsupport.common.S3MockStarter.start(S3MockStarter.java:130)
	at com.adobe.testing.s3mock.junit4.S3MockRule.access$000(S3MockRule.java:42)
	at com.adobe.testing.s3mock.junit4.S3MockRule$1.evaluate(S3MockRule.java:66)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)


```

**Comment by agudian** [comment]
Thanks a lot! I guess we’ll have to disable auto-configs completely...

**Comment by ateebkhawaja** [comment]
I attempted to exclude AutoConfg's using AspectJ filters and Regex, but unfortunately, some of them are needed for loading the context itself. One option is to take every AutoConfig class that from the Spring Docs and put them in but that's an ugly solution. 

Something that came to mind was to have the Rule somehow read the EnableAutoConfiguration annotation from the test class itself. I don't know if this is a possible or not since I am not that familiar with coding for Rules.

**Comment by timoe** [comment]
@ateebkhawaja: Can you give a bit more details on your runtime setup please. I tried the following:

I added
```
	<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-consul-config</artifactId>
			<version>2.0.0.RC1</version>
	</dependency>
```

as a dependency. Doing that causes this exception 
```
com.ecwid.consul.transport.TransportException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8500 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)

	at com.ecwid.consul.transport.AbstractHttpTransport.executeRequest(AbstractHttpTransport.java:77)
	at com.ecwid.consul.transport.AbstractHttpTransport.makeGetRequest(AbstractHttpTransport.java:34)
	at com.ecwid.consul.v1.ConsulRawClient.makeGetRequest(ConsulRawClient.java:128)
	at com.ecwid.consul.v1.kv.KeyValueConsulClient.getKVValues(KeyValueConsulClient.java:150)
	at com.ecwid.consul.v1.ConsulClient.getKVValues(ConsulClient.java:534)
	at org.springframework.cloud.consul.config.ConsulPropertySource.init(ConsulPropertySource.java:66)
	at org.springframework.cloud.consul.config.ConsulPropertySourceLocator.create(ConsulPropertySourceLocator.java:166)
	at org.springframework.cloud.consul.config.ConsulPropertySourceLocator.locate(ConsulPropertySourceLocator.java:132)
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:94)
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:633)
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:373)
```
saying, that Consul can not be reached. 

I then ran Consul via 
`docker run -d -p8500:8500 --name=dev-consul -e CONSUL_BIND_INTERFACE=eth0 consul` 

and my test turns greens without any other adaptions.

**Comment by ateebkhawaja** [comment]
In terms of consul, whether consul is running or not should not cause the test to fail.

In my bootstrap.yml I have the consul disabled, since I don't use it for most Unit Tests. But the s3Mock ignores that and still tries to run consul config and tries to connect.

For Unit Testing, all tests should be able to run offline without any external dependencies. 
Otherwise using S3Mock would not make sense.

**Comment by timoe** [comment]
Of course, makes totally sense to disable Consul during test runs. Thanks for the info, we now can dig deeper.

**Comment by afranken** [comment]
S3Mock 2.2.0 was just released that now includes support for [TestContainers](https://www.testcontainers.org/).
If there is a possibility of running Docker during your build, I would highly suggest migrating to TestContainers.

Using S3MockApplication directly or through one of the unit test modules will always have the risk of breaking because of dependencies that are pulled in by the application that is being tested, and auto configration that is added through Spring Boot updates in the S3Mock.

Using Docker in your tests will insulate both applications dependencies and application life cycles.
