### ISSUE TITLE
`aws-cli` does not work when using https/SSL for connection

### ISSUE THREAD

**Issue by afranken** [adobe/S3Mock#706]
When trying to reproduce #702 by just starting the Docker container locally using

`docker run -p 9090:9090 -p 9191:9191 -e validKmsKeys="arn:aws:kms:us-east-1:1234567890:key/valid-test-key-ref" -e initialBuckets="bucket-a, bucket-b" -e LOGGING_LEVEL_ROOT=DEBUG -t adobe/s3mock:latest`

and then setting up the `aws-cli` by adding the key to the `~/.aws/credentials`:
```
[default]
aws_access_key_id = 1234567890
aws_secret_access_key = valid-test-key-ref
```

and then trying to upload a file:
`aws s3 cp ./test.json s3://bucket-a/ --endpoint-url=https://localhost:9191 --no-verify-ssl`

the following errormessage is returned by the client:
`upload failed: ./test.json to s3://bucket-a/test.json SSL validation failed for https://localhost:9191/bucket-a/test.json [SSL: SSLV3_ALERT_UNEXPECTED_MESSAGE] sslv3 alert unexpected message (_ssl.c:997)`

And the following stack trace can be seen on the server:
```
2022-07-21 17:30:41.380 DEBUG 1 --- [tp1958680465-30] org.eclipse.jetty.io.ssl.SslConnection   : DecryptedEndPoint@4509b41c{l=/172.17.0.2:9191,r=/172.17.0.1:65038,OPEN,fill=-,flush=-,to=120/30000} stored flush exception

javax.net.ssl.SSLProtocolException: No common named group
	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source) ~[na:na]
	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source) ~[na:na]
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source) ~[na:na]
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source) ~[na:na]
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source) ~[na:na]
	at java.base/sun.security.ssl.KeyShareExtension$HRRKeyShareProducer.produce(Unknown Source) ~[na:na]
	at java.base/sun.security.ssl.SSLExtension.produce(Unknown Source) ~[na:na]
	at java.base/sun.security.ssl.SSLExtensions.produce(Unknown Source) ~[na:na]
	at java.base/sun.security.ssl.ServerHello$T13HelloRetryRequestProducer.produce(Unknown Source) ~[na:na]
	at java.base/sun.security.ssl.SSLHandshake.produce(Unknown Source) ~[na:na]
	at java.base/sun.security.ssl.ClientHello$T13ClientHelloConsumer.goHelloRetryRequest(Unknown Source) ~[na:na]
	at java.base/sun.security.ssl.ClientHello$T13ClientHelloConsumer.consume(Unknown Source) ~[na:na]
	at java.base/sun.security.ssl.ClientHello$ClientHelloConsumer.onClientHello(Unknown Source) ~[na:na]
	at java.base/sun.security.ssl.ClientHello$ClientHelloConsumer.consume(Unknown Source) ~[na:na]
	at java.base/sun.security.ssl.SSLHandshake.consume(Unknown Source) ~[na:na]
	at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source) ~[na:na]
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(Unknown Source) ~[na:na]
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(Unknown Source) ~[na:na]
	at java.base/java.security.AccessController.doPrivileged(Unknown Source) ~[na:na]
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(Unknown Source) ~[na:na]
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.fill(SslConnection.java:654) ~[jetty-io-9.4.48.v20220622.jar!/:9.4.48.v20220622]
	at org.eclipse.jetty.server.HttpConnection.fillRequestBuffer(HttpConnection.java:350) ~[jetty-server-9.4.48.v20220622.jar!/:9.4.48.v20220622]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260) ~[jetty-server-9.4.48.v20220622.jar!/:9.4.48.v20220622]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) ~[jetty-io-9.4.48.v20220622.jar!/:9.4.48.v20220622]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) ~[jetty-io-9.4.48.v20220622.jar!/:9.4.48.v20220622]
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:555) ~[jetty-io-9.4.48.v20220622.jar!/:9.4.48.v20220622]
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:410) ~[jetty-io-9.4.48.v20220622.jar!/:9.4.48.v20220622]
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:164) ~[jetty-io-9.4.48.v20220622.jar!/:9.4.48.v20220622]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) ~[jetty-io-9.4.48.v20220622.jar!/:9.4.48.v20220622]
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) ~[jetty-io-9.4.48.v20220622.jar!/:9.4.48.v20220622]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) ~[jetty-util-9.4.48.v20220622.jar!/:9.4.48.v20220622]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) ~[jetty-util-9.4.48.v20220622.jar!/:9.4.48.v20220622]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
```

adding `-Djavax.net.debug=ssl:handshake` to the application adds debug output for the SSL handshake, which reveals that the JRE running the S3Mock application is missing the "named group" needed for TLS 1.3:

```javax.net.ssl|DEBUG|E1|qtp1958680465-30|2022-07-21 17:30:41.353 GMT|null:-1|Consumed extension: supported_versions
javax.net.ssl|DEBUG|E1|qtp1958680465-30|2022-07-21 17:30:41.354 GMT|null:-1|Negotiated protocol version: TLSv1.3
javax.net.ssl|DEBUG|E1|qtp1958680465-30|2022-07-21 17:30:41.358 GMT|null:-1|Consumed extension: psk_key_exchange_modes
javax.net.ssl|DEBUG|E1|qtp1958680465-30|2022-07-21 17:30:41.358 GMT|null:-1|Handling pre_shared_key absence.
2022-07-21 17:30:41.359 DEBUG 1 --- [tp1958680465-30] o.e.jetty.util.ssl.SslContextFactory     : SNI matching for type=host_name (0), value=localhost
2022-07-21 17:30:41.360 DEBUG 1 --- [tp1958680465-30] o.e.jetty.util.ssl.SslContextFactory     : SNI host name localhost
javax.net.ssl|DEBUG|E1|qtp1958680465-30|2022-07-21 17:30:41.360 GMT|null:-1|server name indication (type=host_name (0), value=localhost) is accepted
javax.net.ssl|DEBUG|E1|qtp1958680465-30|2022-07-21 17:30:41.361 GMT|null:-1|Consumed extension: server_name
javax.net.ssl|DEBUG|E1|qtp1958680465-30|2022-07-21 17:30:41.361 GMT|null:-1|Ignore unavailable extension: max_fragment_length
javax.net.ssl|DEBUG|E1|qtp1958680465-30|2022-07-21 17:30:41.362 GMT|null:-1|Ignore unavailable extension: status_request
javax.net.ssl|DEBUG|E1|qtp1958680465-30|2022-07-21 17:30:41.362 GMT|null:-1|Consumed extension: supported_groups
javax.net.ssl|DEBUG|E1|qtp1958680465-30|2022-07-21 17:30:41.362 GMT|null:-1|Ignore unsupported extension: ec_point_formats
javax.net.ssl|DEBUG|E1|qtp1958680465-30|2022-07-21 17:30:41.362 GMT|null:-1|Ignore server unenabled extension: application_layer_protocol_negotiation
javax.net.ssl|DEBUG|E1|qtp1958680465-30|2022-07-21 17:30:41.363 GMT|null:-1|Consumed extension: application_layer_protocol_negotiation
javax.net.ssl|DEBUG|E1|qtp1958680465-30|2022-07-21 17:30:41.363 GMT|null:-1|Ignore unsupported extension: status_request_v2
javax.net.ssl|DEBUG|E1|qtp1958680465-30|2022-07-21 17:30:41.363 GMT|null:-1|Ignore unsupported extension: extended_master_secret
javax.net.ssl|DEBUG|E1|qtp1958680465-30|2022-07-21 17:30:41.364 GMT|null:-1|Ignore unsupported extension: session_ticket
javax.net.ssl|DEBUG|E1|qtp1958680465-30|2022-07-21 17:30:41.364 GMT|null:-1|Consumed extension: signature_algorithms
javax.net.ssl|DEBUG|E1|qtp1958680465-30|2022-07-21 17:30:41.365 GMT|null:-1|Ignore unavailable extension: cookie
javax.net.ssl|DEBUG|E1|qtp1958680465-30|2022-07-21 17:30:41.365 GMT|null:-1|Ignore unavailable extension: certificate_authorities
javax.net.ssl|DEBUG|E1|qtp1958680465-30|2022-07-21 17:30:41.365 GMT|null:-1|Ignore unavailable extension: signature_algorithms_cert
javax.net.ssl|DEBUG|E1|qtp1958680465-30|2022-07-21 17:30:41.365 GMT|null:-1|Ignore unsupported named group: x25519
javax.net.ssl|DEBUG|E1|qtp1958680465-30|2022-07-21 17:30:41.366 GMT|null:-1|Consumed extension: key_share
javax.net.ssl|DEBUG|E1|qtp1958680465-30|2022-07-21 17:30:41.366 GMT|null:-1|Ignore unsupported extension: renegotiation_info
javax.net.ssl|DEBUG|E1|qtp1958680465-30|2022-07-21 17:30:41.367 GMT|null:-1|use cipher suite TLS_AES_256_GCM_SHA384
javax.net.ssl|ERROR|E1|qtp1958680465-30|2022-07-21 17:30:41.374 GMT|null:-1|Fatal (UNEXPECTED_MESSAGE): No common named group (
"throwable" : {
  javax.net.ssl.SSLProtocolException: No common named group```

**Comment by afranken** [comment]
Turns out the module `jdk.crypto.ec` must be present in the JRE running the application. It provides the TLS support we need here.

After adding the module, the `aws cp` command executes successfully:

```
aws s3 cp ./test.json s3://bucket-a/ --endpoint-url=https://localhost:9191 --no-verify-ssl
/usr/local/Cellar/awscli/2.7.17/libexec/lib/python3.10/site-packages/urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
upload: ./test.json to s3://bucket-a/test.json
```
